name: Deploy Swagger API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install necessary packages and dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx python3-pip python3-dev
          pip install -r requirements.txt

      # Set up Nginx configuration
      - name: Set up Nginx
        run: |
          sudo mkdir -p /etc/nginx/conf.d
          echo "
          server {
              listen 80;
              server_name your_domain_or_ip;

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }
          " | sudo tee /etc/nginx/conf.d/swagger_server.conf
          sudo nginx -t
          sudo systemctl reload nginx
          sudo systemctl enable nginx
          sudo systemctl start nginx

      # Start Gunicorn to serve the application
      - name: Start Gunicorn
        run: |
          source /path/to/your/virtualenv/bin/activate
          nohup gunicorn --bind 0.0.0.0:8000 app:app &
          ps aux | grep gunicorn
