name: Deploy Swagger Server to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to the Swagger server directory
            cd /home/ubuntu/swagger_server

            # Pull the latest changes from the repository
            git pull origin main

            # Activate the virtual environment
            source venv/bin/activate

            # Install the required dependencies
            pip install -r requirements.txt

            # Restart the Swagger server service
            sudo systemctl restart swagger_server
          EOF
        env:
          # Pass the necessary secrets as environment variables
          EC2_HOST: ${{ secrets.EC2_HOST }}  # Public IP or DNS of the EC2 instance
