name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH Key for EC2
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private-key.pem
        chmod 600 private-key.pem

    - name: Add EC2 Host to known_hosts to avoid verification issues
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy Python app to EC2
      run: |
        scp -i private-key.pem -o StrictHostKeyChecking=no -r ./app.py ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/your-app-folder

    - name: SSH into EC2 and restart app
      run: |
        ssh -i private-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to the app folder
          cd /home/ubuntu/your-app-folder
          
          # Install Python dependencies
          pip install -r requirements.txt
          
          # Kill any existing Gunicorn processes (if applicable)
          pkill -f 'gunicorn: app'
          
          # Restart the application
          nohup gunicorn -w 4 app:app &  # Modify according to your app structure
        EOF
