name: Deploy Python App with Swagger UI to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Ensure you have a requirements.txt file

    # Step 4: Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_KEY: ${{ secrets.EC2_KEY }}  # Path to your private EC2 key file
      run: |
        # Copy your Python application and Swagger UI files to EC2
        scp -i $EC2_KEY -o StrictHostKeyChecking=no -r ./app.py $EC2_USER@$EC2_HOST:/home/ubuntu/your-app-folder
        
        # SSH into EC2 and perform the necessary steps
        ssh -i $EC2_KEY -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          # Navigate to the app folder
          cd /home/ubuntu/app.py
          
          # Install Python dependencies on EC2 if not already installed
          pip install -r requirements.txt
          
          # Kill the existing app process (if any)
          pkill -f 'gunicorn: app'  # For Flask with Gunicorn
          # Or use the following for FastAPI with Uvicorn:
          # pkill -f 'uvicorn: app'
          
          # Restart the app
          nohup gunicorn -w 4 app:app.py &  # For Flask (replace 'app' with your app file name)
          # Or use this for FastAPI:
          # nohup uvicorn app:app --host 0.0.0.0 --port 8000 &

          # Optionally, you can restart using systemd if you configured it:
          # sudo systemctl restart gunicorn  # If using systemd
        EOF

    # Step 5: Optionally, verify the deployment (optional but recommended)
    - name: Verify Deployment
      run: |
        echo "Deployment complete. Visit your EC2 instance's public IP to access Swagger UI."
