name: Deploy Swagger API to EC2

on:
  push:
    branches:
      - main

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REPO_NAME: ${{ github.repository }}
  DEPLOY_DIR: /home/ubuntu/swagger_server  # Adjust according to your EC2 directory structure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Update packages and install dependencies
            sudo yum update -y
            sudo yum install -y python3 python3-pip git nginx

            # Clone the repository (if it hasn't been cloned already)
            if [ ! -d "$DEPLOY_DIR" ]; then
              git clone https://github.com/${{ github.repository }} $DEPLOY_DIR
            else
              cd $DEPLOY_DIR && git pull
            fi

            cd $DEPLOY_DIR

            # Set up Python environment and install dependencies
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Start the application using Gunicorn
            gunicorn --bind 0.0.0.0:8000 app:app &

            # Configure Nginx to proxy requests to Gunicorn
            sudo rm -f /etc/nginx/conf.d/default.conf
            sudo cp /home/ubuntu/swagger_server/nginx/swagger_server.conf /etc/nginx/conf.d/
            sudo systemctl restart nginx

            # Enable and start Gunicorn as a service
            sudo systemctl enable gunicorn
            sudo systemctl start gunicorn
          EOF

      - name: Verify Deployment
        run: |
          curl http://${{ secrets.EC2_HOST }}:8000/swagger-ui
