name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # You can change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    
    - name: Run Tests (Optional)
      run: |
        source venv/bin/activate
        pytest tests/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Update the server and install necessary packages
          sudo yum update -y
          sudo yum install -y python3 python3-pip git

          # Pull latest code from GitHub
          cd /home/ec2-user
          git pull origin main
          
          # Set up virtual environment
          python3 -m venv venv
          source venv/bin/activate
          
          # Install dependencies
          pip install -r requirements.txt
          
          # Start Gunicorn
          gunicorn --bind 0.0.0.0:8000 app:app &

          # Ensure you have a static folder for Swagger UI
          if [ ! -d "static" ]; then
            mkdir static
          fi

          # You can download or copy swagger-ui assets here (for example)
          curl -o static/swagger-ui.html https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.52.5/swagger-ui-bundle.js
          
          # Restart Gunicorn to pick up any changes
          pkill gunicorn
          gunicorn --bind 0.0.0.0:8000 app:app &
          
          echo "Deployment finished."
